output: "README.md"
header: |+
  [![Go Report Card](https://goreportcard.com/badge/github.com/KEINOS/go-items)](https://goreportcard.com/report/github.com/KEINOS/go-items)
  [![Go Reference](https://pkg.go.dev/badge/github.com/KEINOS/go-items.svg)](https://pkg.go.dev/github.com/KEINOS/go-items/items)

repository:
  url: https://github.com/KEINOS/go-items
  defaultBranch: master
  path: /